### ISSUE TITLE
Docker Image Authentication

### ISSUE THREAD

**Issue by sparevermicelli** [FilenCloudDienste/filen-cli#38]
Hi, 
I am trying to use the available docker image (via Portainer). 
I have the following error(email/password/2fa provided via ENV variables directly in Portainer):

      

node:internal/errors:496

    ErrorCaptureStackTrace(err);

    ^

Error [ERR_USE_AFTER_CLOSE]: readline was closed

    at new NodeError (node:internal/errors:405:5)

    at Interface.question (node:internal/readline/interface:404:13)

    at Interface.question (node:readline:159:5)

    at /filen-cli/filen.js:72146:36

    at new Promise (<anonymous>)

    at prompt (/filen-cli/filen.js:72142:14)

    at Authentication.authenticate (/filen-cli/filen.js:72453:64)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /filen-cli/filen.js:117169:7 {

  code: 'ERR_USE_AFTER_CLOSE'

}

Node.js v18.20.3

**Comment by JupiterPi** [comment]
When you start the CLI without any arguments supplied, [interactive mode](https://github.com/FilenCloudDienste/filen-cli#interactive-mode) starts, which tries to read commands from the terminal. Another possibility is the CLI prompting for a valid 2FA code. The crash happens because theres no stdin in a Docker container. 

Depending on what you're trying to accomplish with the container, try passing the `--webdav`, `--webdav-proxy` or `--s3` flag to the CLI (see [README](https://github.com/FilenCloudDienste/filen-cli#webdav-server)) (in Docker, this could be done as `docker run -p 80:80 -e FILEN_EMAIL=*** -e FILEN_PASSWORD=*** -e FILEN_2FA_CODE=*** filen/cli:v0.0.6 --webdav --w-user myuser --w-password mypassword`).
